version: '2'
services:
  datacontainer:
    image: ubuntu:14.04
    volumes:
      - ./dataset/:/var/dataset
      - ./src/:/home/jovyan/work
      - ./logs/:/tmp/tflogs
      - ./models/:/tmp/tfmodels

  sudo_tensorflow_py3:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    volumes_from:
      - datacontainer

  tensorflow_py3:
    build:
      context: .
      dockerfile: Dockerfile
    volumes_from:
      - datacontainer